layout_spectrum: 0.9784808
typography_spectrum: 0.04850883
color:
  saturation: 0.2598423
  lightness: 0.2968961
  brandStrength: 0.2760812
  rhythmicContrast: 0.3460286
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Review 55
